spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  session:
    timeout: {SESSION_TIMEOUT}
    store-type: jdbc
    jdbc:
      initialize-schema: always

web:
  allowed-origins: ${ALLOWED_ORIGINS}

server:
  servlet:
    session:
      timeout: {SESSION_TIMEOUT}
      tracking-modes: cookie
      http-only: {SESSION_HTTP_ONLY:false}
      secure: false
      name: JSESSIONID
      domain: {SESSION_COOKIE_DOMAIN}
      path: /
      max-age: 600
      same-site: strict